version: "3.4"

services:
  mysqldb:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=achatdb
      - MYSQL_PASSWORD=root
    ports:
      - '3306:3306'
    volumes:
      - db_vol:/var/lib/mysql:rw
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - common-net

  backend:
    container_name: 'backendserver'
    image: imenrais/backend:1.1
    ports:
      - '8089:8089'
    restart: unless-stopped
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/achatdb?autoReconnect=true&failOverReadOnly=false&maxReconnects=10
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      mysqldb:
        condition: service_healthy
    networks:
      - common-net

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - common-net

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
      - grafana_config:/etc/grafana
      - grafana_plugins:/var/lib/grafana/plugins
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - common-net

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    image: jenkins-with-maven
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    networks:
      - common-net

volumes:
  db_vol:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  nexus_data:
  prometheus_config:
  prometheus_data:
  grafana_data:
  grafana_config:
  grafana_plugins:
  jenkins_home:

networks:
  common-net:
    driver: bridge

